# Blue Matrix theme colors for Hyprland

general {
    # Blue Matrix theme colors
    col.active_border = rgba(00b0ffee) rgba(76c1ffee) 45deg  # blue to cyan gradient
    col.inactive_border = rgba(68686899)  # gray
}

decoration {
    shadow {
        color = rgba(10111699)  # blue matrix bg color with transparency
    }
}
