# Blue Matrix colour scheme for tmux

# Status bar general styling
set -g status-style fg=#00a2ff,bg=#101116

# Active window in status bar
set-window-option -g window-status-current-style bg=#00b0ff,fg=#101116

# Inactive windows in status bar
set-window-option -g window-status-style fg=#686868,bg=#101116

# Pane border colours
set -g pane-border-style fg=#686868
set -g pane-active-border-style fg=#00b0ff

# Message styling
set -g message-style fg=#00a2ff,bg=#101116
set -g message-command-style fg=#00a2ff,bg=#101116
