# Vague colour scheme for tmux

# Status bar general styling
set -g status-style fg=#cdcdcd,bg=#18191a

# Active window in status bar
set-window-option -g window-status-current-style bg=#f29e74,fg=#18191a

# Inactive windows in status bar
set-window-option -g window-status-style fg=#6e6e6e,bg=#18191a

# Pane border colours
set -g pane-border-style fg=#2a2a2a
set -g pane-active-border-style fg=#f29e74

# Message styling
set -g message-style fg=#cdcdcd,bg=#18191a
set -g message-command-style fg=#cdcdcd,bg=#18191a
