# Blue Matrix theme for Kitty
# vim:ft=kitty
## name:     Blue Matrix
## blurb:    A vibrant blue and neon colorscheme

foreground               #00a2ff
background               #101116
selection_foreground     #101116
selection_background     #c1deff
cursor                   #76ff9f
url_color                #76c1ff

active_border_color #76c1ff
inactive_border_color #686868

color0   #101116
color8   #686868
color1   #ff5680
color9   #ff6e67
color2   #00ff9c
color10  #5ffa68
color3   #fffc58
color11  #fffc67
color4   #00b0ff
color12  #6871ff
color5   #d57bff
color13  #d682ec
color6   #76c1ff
color14  #60fdff
color7   #c7c7c7
color15  #ffffff

active_tab_foreground    #00a2ff
active_tab_background    #101116
inactive_tab_foreground  #686868
inactive_tab_background  #101116
